services:
  php:
    build:
      context: .
      dockerfile: ./ezstock/Dockerfile
    container_name: php
    restart: unless-stopped
    ports:
      - "9000:9000"
    volumes:
      - ./ezstock/:/var/www/html
    networks:
      - symfony_network
    depends_on:
      - mariadb
      - rabbitmq
      - alphavantage
    environment:
      - APP_ENV=${ENV}
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./infrastructure/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./ezstock:/var/www/html
    networks:
      - symfony_network
    depends_on:
      - php
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    restart: unless-stopped
    environment:
      - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
      - MARIADB_DATABASE=${MARIADB_DATABASE}
      - MARIADB_USER=${MARIADB_USER}
      - MARIADB_PASSWORD=${MARIADB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - symfony_network
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: unless-stopped
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - symfony_network
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
    depends_on:
      - mailhog
  alphavantage:
    build: 
      context: .
      dockerfile: assets/json_server/Dockerfile
    container_name: alphavantage
    ports:
      - "3000:3000"
    networks:
      - symfony_network
    volumes:
      - ./assets/json_server/:/server/
  mailhog:
    image: mailhog/mailhog:latest
    container_name: mailhog
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - symfony_network

networks:
  symfony_network:
    driver: bridge

volumes:
  db_data:
