# config/packages/messenger.yaml
parameters:
    messenger_dns: '%env(MESSENGER_TRANSPORT_DSN)%'

framework:
    messenger:
        transports:
            amqp:
                dsn: '%messenger_dns%'
                options:
                    exchange:
                        name: 'messages'
                        type: direct
                    queues:
                        stock_quote_queue: ~
        routing:
            'App\Message\StockEmailMessage': amqp
